<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-02T18:51:32 IST" name="Suite" finished-at="2023-10-02T18:51:57 IST" duration-ms="25487">
    <groups>
      <group name="Master">
        <method signature="TC_001_AccountRegistration.test_Account_Reg()[pri:0, instance:testCases.TC_001_AccountRegistration@179ece50]" name="test_Account_Reg" class="testCases.TC_001_AccountRegistration"/>
        <method signature="TC_001_LoginTest.testLogin()[pri:0, instance:testCases.TC_001_LoginTest@1a677343]" name="testLogin" class="testCases.TC_001_LoginTest"/>
      </group> <!-- Master -->
      <group name="Sanity">
        <method signature="TC_001_LoginTest.testLogin()[pri:0, instance:testCases.TC_001_LoginTest@1a677343]" name="testLogin" class="testCases.TC_001_LoginTest"/>
      </group> <!-- Sanity -->
      <group name="Regression">
        <method signature="TC_001_AccountRegistration.test_Account_Reg()[pri:0, instance:testCases.TC_001_AccountRegistration@179ece50]" name="test_Account_Reg" class="testCases.TC_001_AccountRegistration"/>
      </group> <!-- Regression -->
    </groups>
    <test started-at="2023-10-02T18:51:32 IST" name="Test" finished-at="2023-10-02T18:51:57 IST" duration-ms="25487">
      <class name="testCases.TC_001_LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.TC_001_LoginTest@1a677343]" started-at="2023-10-02T18:51:38 IST" name="setup" finished-at="2023-10-02T18:51:46 IST" duration-ms="8089" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testLogin()[pri:0, instance:testCases.TC_001_LoginTest@1a677343]" started-at="2023-10-02T18:51:46 IST" name="testLogin" finished-at="2023-10-02T18:51:57 IST" duration-ms="11020" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at testCases.TC_001_LoginTest.testLogin(TC_001_LoginTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC_001_LoginTest@1a677343]" started-at="2023-10-02T18:51:57 IST" name="tearDown" finished-at="2023-10-02T18:51:57 IST" duration-ms="95" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC_001_LoginTest -->
      <class name="testCases.TC_001_AccountRegistration">
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.TC_001_AccountRegistration@179ece50]" started-at="2023-10-02T18:51:32 IST" name="setup" finished-at="2023-10-02T18:51:36 IST" duration-ms="4136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test_Account_Reg()[pri:0, instance:testCases.TC_001_AccountRegistration@179ece50]" started-at="2023-10-02T18:51:36 IST" name="test_Account_Reg" finished-at="2023-10-02T18:51:37 IST" duration-ms="1612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Account_Reg -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC_001_AccountRegistration@179ece50]" started-at="2023-10-02T18:51:38 IST" name="tearDown" finished-at="2023-10-02T18:51:38 IST" duration-ms="98" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC_001_AccountRegistration -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
